
name: Java CI with Maven

on:
  push:
    branches: [ "feature/*", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.9
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.1+10'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
